// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpUxh3dXWhu-uPm0PMzfRS5DHDN1xvY9w',
    appId: '1:1030055158509:web:e1bec29c2fd8807e4862e4',
    messagingSenderId: '1030055158509',
    projectId: 'autismdetection-86fc0',
    authDomain: 'autismdetection-86fc0.firebaseapp.com',
    storageBucket: 'autismdetection-86fc0.firebasestorage.app',
    measurementId: 'G-81DYWRXN6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8YFYTSIw7DXxeeQ-Olf5IuePXfQJekgo',
    appId: '1:1030055158509:android:d362b5269d3626564862e4',
    messagingSenderId: '1030055158509',
    projectId: 'autismdetection-86fc0',
    storageBucket: 'autismdetection-86fc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT7sb2XvmbDENZ1pd2B2FuqLMm4lb2XgQ',
    appId: '1:1030055158509:ios:7c50aed17689f5d24862e4',
    messagingSenderId: '1030055158509',
    projectId: 'autismdetection-86fc0',
    storageBucket: 'autismdetection-86fc0.firebasestorage.app',
    iosBundleId: 'com.example.mlautismdetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT7sb2XvmbDENZ1pd2B2FuqLMm4lb2XgQ',
    appId: '1:1030055158509:ios:7c50aed17689f5d24862e4',
    messagingSenderId: '1030055158509',
    projectId: 'autismdetection-86fc0',
    storageBucket: 'autismdetection-86fc0.firebasestorage.app',
    iosBundleId: 'com.example.mlautismdetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpUxh3dXWhu-uPm0PMzfRS5DHDN1xvY9w',
    appId: '1:1030055158509:web:de4cef6bc1b9cc7c4862e4',
    messagingSenderId: '1030055158509',
    projectId: 'autismdetection-86fc0',
    authDomain: 'autismdetection-86fc0.firebaseapp.com',
    storageBucket: 'autismdetection-86fc0.firebasestorage.app',
    measurementId: 'G-V9K7TLBR8D',
  );
}
